inherit_from:
 - rubocop-todo.yml
 - .rubocop-cocoapods.yml

#- Core -----------------------------------------------------------------------

AllCops:
  Exclude:
    - spec/fixtures/**/*
    - lib/cocoapods-core/vendor/**/*

FileName:
  Exclude:
    - lib/cocoapods-core.rb
