AllCops:
  Include:
    - Rakefile
  Exclude:
    - lib/cocoapods-core/vendor/**
    - spec/fixtures/**

# Remove once the support for Ruby 1.8.7 has been phased out
HashSyntax:
  EnforcedStyle: hash_rockets

StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

SignalException:
  EnforcedStyle: only_raise

ConstantName:
  Enabled: false

IfUnlessModifier:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

AsciiComments:
  Enabled: false

Proc:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

Encoding:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

FileName:
  Enabled: false

AssignmentInCondition:
  Enabled: false

RescueException:
  Enabled: false

TrivialAccessors:
  Enabled: false

NonNilCheck:
  Enabled: false

#------------------------------------------------------------------------------
# Needs fixing
#------------------------------------------------------------------------------

CyclomaticComplexity:
  Max: 6
  Max: 11

ClassLength:
  Max: 100
  Max: 280

MethodLength:
  Max: 10
  Max: 27

LineLength:
  Max: 80
  Max: 120

Documentation:
  Enabled: false

Lambda:
  Exclude:
    - spec/**

Blocks:
  Exclude:
    - spec/**

Semicolon:
  Exclude:
    - spec/**

Void:
  Exclude:
    - spec/**

UselessAssignment:
  Exclude:
    - spec/**

AmbiguousRegexpLiteral:
  Exclude:
    - spec/**

EmptyLines:
  Exclude:
    - spec/**

SpaceBeforeFirstArg:
  Exclude:
    - spec/**
