language: ruby
bundler_args: --without debugging documentation

addons:
 code_climate:
   repo_token: 186c49521e629c51591c86f057f49fe388ce87603e04b5486f0c92f26f2a455f

rvm:
  - 2.0.0

env:
  - LANG="en_US.UTF-8"

script: bundle exec rake spec

