language: ruby
rvm:
  - 1.8.7
  - 1.9.3
before_install: git submodule update --init && cd external/Xcodeproj && rake ext:install_opencflite_debs
script: pwd && rake -T && bundle exec rake spec:travis
