language: ruby
rvm:
  - 1.8.7
  - 1.9.3
install: git submodule update --init && bundle install --path bundle && pushd . && cd bundle/ruby/*/bundler/gems/Xcodeproj-* && rake travis:setup && popd && sudo apt-get install subversion
script: bundle exec rake spec
